### ISSUE TITLE
Function in props always wrapped in $appy()

### ISSUE THREAD

**Issue by artaommahe** [ngReact/ngReact#129]
https://github.com/ngReact/ngReact/blob/master/ngReact.js#L158
https://github.com/ngReact/ngReact/blob/master/ngReact.js#L60

Any function passed to component props wrapped with $scope.$apply. So on each props.func() call we will triger digest cycle even if it's simple function that does not change any digest value. It is huge performance drop. Maybe add directive option that will skip $scope.$apply() wrapper for props functions?

e.x. from current app, react items list with ~250 items(images with text)
with props function call - http://i.imgur.com/vN5zZHu.png (1.48 s)
without - http://i.imgur.com/Q4G0ISr.png (298.41 ms)

**Comment by kasperp** [comment]
@artaommahe thanks for the issue. That sounds like a good idea, is it something you would like to submit a pull request for ?

**Comment by spalger** [comment]
This isn't a perfect solution, but I've gotten around it the issue by wrapping non-"action" type methods in a "helpers" object so they won't get wrapped.

Perhaps it would make sense to expose an `actions` argument to the `react-component

**Comment by spalger** [comment]
This isn't a perfect solution, but I've gotten around it the issue by wrapping non-"action" type methods in a "helpers" object so they won't get wrapped.

Perhaps it would make sense to expose an `actions` argument to the `react-component` directive that would wrap functions passed in. Functions in `props` would no longer be wrapped, and `actions` wouldn't be watched...

**Comment by kasperp** [comment]
Anyone interested in attempting a fix for this?

**Comment by spalger** [comment]
I'd gladly work up a fix. Mind describing how you see it working?

**Comment by spalger** [comment]
Another option might be to batch the digest triggers using requestAnimationFrame, setImmediate, or something.

**Comment by kasperp** [comment]
> Perhaps it would make sense to expose an actions argument to the react-component directive that would wrap functions passed in. Functions in props would no longer be wrapped, and actions wouldn't be watched...

I think this sounds like a good idea. I'm would prefer something that didn't break backwards compatibility. So "Functions in props would no longer be wrapped" is a little problematic, so perhaps add a `noWrappedProps` instead of automatically not wrapping. 

An alterative approach could be to allow users to add an property on the functions they pass in to props that hold this information so something like:

```javascript
$scope.onClick = function() { .. }
$scope.onClick.noWatch = true;

$scope.format = function() { }
$scope.format.noWrap = true;
```

or 

```javascript
$scope.onClick = function() { .. }
$scope.onClick.ngReact = { noWatch: true }

$scope.format = function() { }
$scope.format.ngReact = { noWrap: true }
```

What do you think, other approaches that would be easier/better ?

**Comment by spalger** [comment]
> I'm would prefer something that didn't break backwards compatibility. 

I agree, and I'm not totally against the `noWrappedProps` idea, but would hope that both the current way of doing things and the new "actions" way both worked out of the box. This might be a bit complex though, you're call.

Continue to wrap the functions in props, BWC mode:
```html
<react-component props="props">
```

Don't wrap the functions in props because actions were defined:
```html
<react-component props="props" actions="actions">
```

Don't wrap the functions in props because of `only-wrap-actions` attribute:
```html
<react-component props="props" actions="actions" only-wrap-actions="false">
```

**Comment by kasperp** [comment]
@spalger sorry for the late response. 

I see what you mean now with maintaining the existing functionality unless the actions are defined. I'm worried that it will be easy to misunderstand, that the behaviour of functions on props is determined by setting another "unrelated" attribute. 

What do you think?

**Comment by spalger** [comment]
Yeah, I agree it would be confusing

**Comment by tvooo** [comment]
I'm interested in this too. I just stumbled upon a situation where this was really, really expensive, as I passed in a filter function to the component which gets called several times. I managed to avoid this performance issue as described by @spalger by wrapping the function in an object, but that's only possible because I control the React component's code. There are plenty of situations out there where this is not possible.

Have you thought of a solution? I have a feeling that this could be addressed in the reactDirective factory. You could, for example, provide an array of props you want watched/$apply'd. Just my two cents.

**Comment by kasperp** [comment]
@tvooo thanks for your contribution. Do you want to give your idea a go in a pull request ?

**Comment by sudheerDev** [comment]
@kasperp any update on this? I have quite a lot of functions wrapped in props. Would be great if they are not being watched. Is there a pull req i can try and profile?

**Comment by mhdmazaz** [comment]
Hi guys,

I would like to contribute and give it a try . providing an array of props you want to be unwatched  ?
What do you think ?

**Comment by kasperp** [comment]
Fixed in #185

**Comment by ghermeto** [comment]
@kasperp I don't think that #185 fixes this issue. Per @rosston comment: 

> This also provides an easy API path forward for #129. $apply or wrappedInApply or something similar could be another option that gets defined per prop, just like watchDepth. I imagine I'll be needing that soon, so I can open a separate PR for that functionality if desired.

In fact, you can see that the function [applyFunctions](https://github.com/ngReact/ngReact/blob/master/ngReact.js#L80) is still called (no matter what) 
on: https://github.com/ngReact/ngReact/blob/master/ngReact.js#L176
and  on: https://github.com/ngReact/ngReact/blob/master/ngReact.js#L245

I will send a PR from my fork.

**Comment by rosston** [comment]
@ghermeto You are correct. I didn't fix this issue in #185. Doing so has been on my to-do list for a month or so. 🙂 #191 looks great!

**Comment by rosston** [comment]
For anyone watching/looking at this issue:

This was for real fixed in #191 and released in 0.4.1.
